---
- name: Install Default Apache on Ububntu
  hosts: ubuntu_servers
  become: yes

  tasks:
  - name: install apache webserver
    apt: name=apache2 state=latest

  - name: start apache
    service: name=apache2 state=started enabled=yes
