---
- name: Loop Test
  hosts: linux1
  become: yes

  tasks:
  - name: Say hi to all
    debug: msg="Hello {{ item }} "
    loop: 
      - "Vasys"
      - "Petya"
      - "Katya"

  - name: until example
    shell: echo -n A >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("AAAA") == false

  - name: print output
    debug:
      var: output.stdout

#  - name: Install many packages Deb 
#    apt: name={{ item }} state=installed
#    loop: 
#      - package1
#      - package2

  
