---
# tasks file for deploy_apache_web
- block: #====REDHAT BLOCK====

      - name: Install Apache for RedHat
        yum: name=httpd state=latest

      - name: Copy project
        copy: src={{source_files}} dest={{destination}} mode=0555
        notify: Restart Apache

      - name: Start Apache and enable for RedHat
        service: name=httpd state=started enabled=yes

  when: redhat
  
- block: #============DEBIAN===========
     - name: install apache for deb
       apt: name=apache2 state=latest

     - name: start webserver and enable for deb
       service: name=apache2 state=started enabled=yes

  when: debian


- name: Copy project
  copy: src={{ item }} dest={{ destination }} mode=0555
  loop:
    - "index.html"
    - "index.php"
    - "main.js"
  notify:
    - Restart Apache for redhat
    - Restart Apache for debian
